// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GpuInfo {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub vram_mb: u64,
    #[prost(enumeration = "GpuBackend", tag = "3")]
    pub backend: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CpuInfo {
    #[prost(string, tag = "1")]
    pub model: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub cores: u32,
    #[prost(uint32, tag = "3")]
    pub threads: u32,
    #[prost(uint64, tag = "4")]
    pub freq_mhz: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkerCapabilities {
    #[prost(string, tag = "1")]
    pub peer_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub gpus: ::prost::alloc::vec::Vec<GpuInfo>,
    #[prost(message, optional, tag = "3")]
    pub cpu: ::core::option::Option<CpuInfo>,
    #[prost(uint64, tag = "4")]
    pub ram_mb: u64,
    #[prost(uint64, tag = "5")]
    pub disk_mb: u64,
    #[prost(string, tag = "6")]
    pub os: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub worker_version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JobSpec {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub hirer_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub max_duration_secs: u64,
    #[prost(uint64, tag = "4")]
    pub memory_limit_mb: u64,
    #[prost(uint64, tag = "5")]
    pub cpu_limit_percent: u64,
    #[prost(enumeration = "GpuBackend", tag = "6")]
    pub required_backend: i32,
    #[prost(string, tag = "7")]
    pub image_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "8")]
    pub image_size_bytes: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JobAssignment {
    #[prost(message, optional, tag = "1")]
    pub spec: ::core::option::Option<JobSpec>,
    #[prost(string, tag = "2")]
    pub master_peer_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JobAccepted {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JobRejected {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogLine {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub timestamp_ms: i64,
    #[prost(enumeration = "LogLevel", tag = "3")]
    pub level: i32,
    #[prost(string, tag = "4")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransferChunk {
    #[prost(string, tag = "1")]
    pub transfer_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub offset: u64,
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "4")]
    pub is_last: bool,
    #[prost(string, tag = "5")]
    pub sha256: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransferAck {
    #[prost(string, tag = "1")]
    pub transfer_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub offset: u64,
    #[prost(bool, tag = "3")]
    pub ok: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JobCompleted {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub success: bool,
    #[prost(string, tag = "3")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub duration_secs: u64,
    #[prost(uint64, tag = "5")]
    pub result_size_bytes: u64,
    /// Full stdout/stderr of the job execution, used for terminal log replay.
    #[prost(string, tag = "6")]
    pub output: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HeartBeat {
    #[prost(string, tag = "1")]
    pub peer_id: ::prost::alloc::string::String,
    #[prost(float, tag = "2")]
    pub uptime_percent: f32,
    #[prost(bool, tag = "3")]
    pub is_busy: bool,
    #[prost(uint64, tag = "4")]
    pub jobs_completed: u64,
}
/// Envelope for framing messages on P2P streams
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Envelope {
    #[prost(oneof = "envelope::Payload", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9")]
    pub payload: ::core::option::Option<envelope::Payload>,
}
/// Nested message and enum types in `Envelope`.
pub mod envelope {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "1")]
        WorkerCapabilities(super::WorkerCapabilities),
        #[prost(message, tag = "2")]
        JobAssignment(super::JobAssignment),
        #[prost(message, tag = "3")]
        JobAccepted(super::JobAccepted),
        #[prost(message, tag = "4")]
        JobRejected(super::JobRejected),
        #[prost(message, tag = "5")]
        LogLine(super::LogLine),
        #[prost(message, tag = "6")]
        TransferChunk(super::TransferChunk),
        #[prost(message, tag = "7")]
        TransferAck(super::TransferAck),
        #[prost(message, tag = "8")]
        JobCompleted(super::JobCompleted),
        #[prost(message, tag = "9")]
        HeartBeat(super::HeartBeat),
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum GpuBackend {
    CpuOnly = 0,
    Cuda = 1,
    Metal = 2,
    Rocm = 3,
}
impl GpuBackend {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::CpuOnly => "CPU_ONLY",
            Self::Cuda => "CUDA",
            Self::Metal => "METAL",
            Self::Rocm => "ROCM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CPU_ONLY" => Some(Self::CpuOnly),
            "CUDA" => Some(Self::Cuda),
            "METAL" => Some(Self::Metal),
            "ROCM" => Some(Self::Rocm),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LogLevel {
    Stdout = 0,
    Stderr = 1,
    System = 2,
}
impl LogLevel {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Stdout => "STDOUT",
            Self::Stderr => "STDERR",
            Self::System => "SYSTEM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STDOUT" => Some(Self::Stdout),
            "STDERR" => Some(Self::Stderr),
            "SYSTEM" => Some(Self::System),
            _ => None,
        }
    }
}
